language: java
script: mvn install
deploy:
  provider: releases
  api_key:
    secure: 
    s4xAkpt6zPD8tEE8i+QnJoy9oRrGYr8xRdEzsQPfVD21ro4k8e6cwQabdePj8h3eupLMx69CVn9dUZDBA4jwFYM1czozNHrg/XIv/bncMNqmHwBOI7H3sHiWMJCamZqDml+8PfKpG5ck26Zk7uomVIZ2pcSpYnY15HUKP7jFY2c7L13tcSso0Kej9Pt7R4PZ1zC0Rp94sioNTKNKJeJSEre+Bc+IuoKrx5YEeyta9CT4BBwsesvkQUF9KtQEpJfXVYGS19sdjHHjqchPzTagkvZxV3ajwCk0ZDXBVlwY86J066WN4e5NbN5ztWlACYgOql28W4ZIBP7LC1UEiKoolIqcyeKrxQ4qEkFrEooiBtOFukhxvKOmiYOwDmk2+Qv2hmGRYnxBzMV/xIxTd+CIc49ICphQw0W6VnAdhA9JNvN3I4n6vwsRHohDp4yNiWKGwuEUd9m1IGYkNZhSvwZUJvYKArEM8QVokSikiIZC+RA+sO2gvUtq+4iXygbP40sb9qDc3TR5k/F4X9MYXdER2oHzlFxLHJP9gm8eDLHY3WxFrgmOmGeliWH93aiAsqeaD/+xLcsCvQYQldbH4Z2elEmwhC5wTwpYpkC28oXaUkEzm8/gexyeGZxwlegWiUFlD6qwivRuTB9oALnY4Baj2zd38h5aC8VnwEV5lrGzJ4c=
  file: "/home/travis/.m2/repository/ch/bbw/sst/ConsoleCalculator/1.0-SNAPSHOT/ConsoleCalculator-1.0-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    tags: true